In [1]:
# upoload csv
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv

In [3]:
import pandas as pd
df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
# select four features
x=df[['CreditScore', 'Age','Balance','EstimatedSalary']]
y=df['Exited']

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [9]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [11]:
model=keras.Sequential([
    keras.layers.Dense(16,activation='relu',input_shape=(4,)),
    keras.layers.Dense(8,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [13]:
history=model.fit(
    x_train,y_train,
    epochs=50,
    validation_split=0.2,
    batch_size=32
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7952 - loss: 0.4938 - val_accuracy: 0.7881 - val_loss: 0.4549
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7942 - loss: 0.4471 - val_accuracy: 0.7956 - val_loss: 0.4476
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7991 - loss: 0.4434 - val_accuracy: 0.7937 - val_loss: 0.4443
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8006 - loss: 0.4412 - val_accuracy: 0.7981 - val_loss: 0.4423
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8011 - loss: 0.4397 - val_accuracy: 0.7969 - val_loss: 0.4413
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8023 - loss: 0.4384 - val_accuracy: 0.7962 - val_loss: 0.4400
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8020 - loss: 0.4377 - val_accuracy: 0.7975 - val_loss: 0.4397
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8025 - loss: 0.4370 - val_accuracy: 0.7956 - val_loss: 0.4382
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8033 - loss: 0.4363 - val_accuracy: 0.7981 - val_loss: 0.4376
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8036 - loss: 0.4356 - val_accuracy: 0.8019 - val_loss: 0.4372
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8045 - loss: 0.4355 - val_accuracy: 0.8025 - val_loss: 0.4360
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8041 - loss: 0.4346 - val_accuracy: 0.8062 - val_loss: 0.4356
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8067 - loss: 0.4343 - val_accuracy: 0.8081 - val_loss: 0.4350
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8047 - loss: 0.4337 - val_accuracy: 0.8094 - val_loss: 0.4347
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8039 - loss: 0.4331 - val_accuracy: 0.8087 - val_loss: 0.4340
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8052 - loss: 0.4328 - val_accuracy: 0.8087 - val_loss: 0.4327
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8067 - loss: 0.4323 - val_accuracy: 0.8056 - val_loss: 0.4326
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8058 - loss: 0.4317 - val_accuracy: 0.8094 - val_loss: 0.4328
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8092 - loss: 0.4312 - val_accuracy: 0.8144 - val_loss: 0.4318
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8098 - loss: 0.4310 - val_accuracy: 0.8119 - val_loss: 0.4326
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8073 - loss: 0.4306 - val_accuracy: 0.8100 - val_loss: 0.4321
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8095 - loss: 0.4300 - val_accuracy: 0.8125 - val_loss: 0.4329
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8102 - loss: 0.4301 - val_accuracy: 0.8119 - val_loss: 0.4307
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8098 - loss: 0.4295 - val_accuracy: 0.8100 - val_loss: 0.4301
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8102 - loss: 0.4294 - val_accuracy: 0.8119 - val_loss: 0.4302
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8092 - loss: 0.4291 - val_accuracy: 0.8112 - val_loss: 0.4308
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8089 - loss: 0.4287 - val_accuracy: 0.8094 - val_loss: 0.4316
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8097 - loss: 0.4286 - val_accuracy: 0.8125 - val_loss: 0.4301
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8087 - loss: 0.4283 - val_accuracy: 0.8094 - val_loss: 0.4303
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8108 - loss: 0.4282 - val_accuracy: 0.8100 - val_loss: 0.4299
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8102 - loss: 0.4278 - val_accuracy: 0.8081 - val_loss: 0.4305
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8094 - loss: 0.4278 - val_accuracy: 0.8087 - val_loss: 0.4297
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8097 - loss: 0.4279 - val_accuracy: 0.8087 - val_loss: 0.4300
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8086 - loss: 0.4272 - val_accuracy: 0.8075 - val_loss: 0.4319
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8105 - loss: 0.4274 - val_accuracy: 0.8094 - val_loss: 0.4307
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8105 - loss: 0.4273 - val_accuracy: 0.8119 - val_loss: 0.4298
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8117 - loss: 0.4273 - val_accuracy: 0.8075 - val_loss: 0.4307
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8117 - loss: 0.4271 - val_accuracy: 0.8069 - val_loss: 0.4299
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8100 - loss: 0.4275 - val_accuracy: 0.8069 - val_loss: 0.4304
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8105 - loss: 0.4267 - val_accuracy: 0.8037 - val_loss: 0.4313
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8098 - loss: 0.4268 - val_accuracy: 0.8044 - val_loss: 0.4308
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8109 - loss: 0.4272 - val_accuracy: 0.8069 - val_loss: 0.4315
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8102 - loss: 0.4271 - val_accuracy: 0.8081 - val_loss: 0.4307
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8103 - loss: 0.4268 - val_accuracy: 0.8081 - val_loss: 0.4295
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8117 - loss: 0.4264 - val_accuracy: 0.8081 - val_loss: 0.4300
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8111 - loss: 0.4264 - val_accuracy: 0.8094 - val_loss: 0.4297
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8145 - loss: 0.4259 - val_accuracy: 0.8100 - val_loss: 0.4287
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8131 - loss: 0.4269 - val_accuracy: 0.8056 - val_loss: 0.4297
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8133 - loss: 0.4266 - val_accuracy: 0.8100 - val_loss: 0.4296
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8123 - loss: 0.4263 - val_accuracy: 0.8075 - val_loss: 0.4304

In [14]:
accuracy,loss=model.evaluate(x_test,y_test)
print(accuracy,loss)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8095 - loss: 0.4243
0.42433252930641174 0.809499979019165

In [16]:
prediction=model.predict(x_test)
predictions=(prediction>0.5)
print(predictions[:10])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]]

Iris dataset

In [31]:
# import iris dataset
from sklearn.datasets import load_iris
iris=load_iris()

In [32]:
print(iris.data)
print(iris.target)
x=iris.data
y=iris.target

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2
,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [34]:
model=keras.Sequential([
    keras.layers.Dense(6,activation='relu',input_shape=(4,)),
    keras.layers.Dense(6,activation='relu'),
    keras.layers.Dense(3,activation='softmax')
])

In [35]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3750 - loss: 1.1332
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4000 - loss: 1.1186
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4000 - loss: 1.1043
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4250 - loss: 1.0907
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4583 - loss: 1.0766
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4667 - loss: 1.0639
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4750 - loss: 1.0512
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5083 - loss: 1.0382
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.0256
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5250 - loss: 1.0138
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5417 - loss: 1.0016
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5667 - loss: 0.9899
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6083 - loss: 0.9785
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6333 - loss: 0.9670
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6417 - loss: 0.9552
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6333 - loss: 0.9442
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6417 - loss: 0.9329
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6500 - loss: 0.9212
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6500 - loss: 0.9097
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6583 - loss: 0.8977
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6583 - loss: 0.8856
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6667 - loss: 0.8737
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6750 - loss: 0.8618
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6750 - loss: 0.8493
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.8368
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.8249
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6833 - loss: 0.8120
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.8004
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.7873
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.7755
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6833 - loss: 0.7628
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.7503
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.7383
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.7257
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6917 - loss: 0.7134
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6917 - loss: 0.7018
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6896
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6783
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6669
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6917 - loss: 0.6555
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6446
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6336
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.6232
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6917 - loss: 0.6131
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6917 - loss: 0.6031
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 0.5936
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7000 - loss: 0.5842
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5753
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7000 - loss: 0.5667
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5583
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5504
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5427
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7000 - loss: 0.5354
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5282
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7000 - loss: 0.5216
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7000 - loss: 0.5148
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7083 - loss: 0.5086
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7167 - loss: 0.5025
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7167 - loss: 0.4967
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7167 - loss: 0.4910
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7167 - loss: 0.4856
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7417 - loss: 0.4803
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7417 - loss: 0.4753
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7583 - loss: 0.4703
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7750 - loss: 0.4656
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7750 - loss: 0.4609
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - loss: 0.4562
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - loss: 0.4518
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7917 - loss: 0.4475
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - loss: 0.4434
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7917 - loss: 0.4388
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8083 - loss: 0.4345
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8167 - loss: 0.4300
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8167 - loss: 0.4255
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8250 - loss: 0.4209
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8250 - loss: 0.4167
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8250 - loss: 0.4123
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8417 - loss: 0.4083
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8500 - loss: 0.4042
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8500 - loss: 0.4003
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8500 - loss: 0.3966
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8500 - loss: 0.3928
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8500 - loss: 0.3892
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8500 - loss: 0.3858
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8500 - loss: 0.3821
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8583 - loss: 0.3790
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8667 - loss: 0.3753
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8667 - loss: 0.3721
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8667 - loss: 0.3687
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8667 - loss: 0.3656
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8667 - loss: 0.3622
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8667 - loss: 0.3592
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8667 - loss: 0.3559
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8667 - loss: 0.3527
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8667 - loss: 0.3496
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8750 - loss: 0.3464
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8750 - loss: 0.3435
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8750 - loss: 0.3404
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3372
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3341

In [36]:
test_loss,test_acc=model.evaluate(x_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - accuracy: 0.8000 - loss: 0.4199

Forest dataset

In [37]:
# upoload csv
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [38]:
df2=pd.read_csv('train.csv')

In [39]:
df2.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,1,2596,51,3,258,0,510,221,232,148,...,0,0,0,0,0,0,0,0,0,5
1,2,2590,56,2,212,-6,390,220,235,151,...,0,0,0,0,0,0,0,0,0,5
2,3,2804,139,9,268,65,3180,234,238,135,...,0,0,0,0,0,0,0,0,0,2
3,4,2785,155,18,242,118,3090,238,238,122,...,0,0,0,0,0,0,0,0,0,2
4,5,2595,45,2,153,-1,391,220,234,150,...,0,0,0,0,0,0,0,0,0,5

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  15120 non-null  int64
 1   Elevation                           15120 non-null  int64
 2   Aspect                              15120 non-null  int64
 3   Slope                               15120 non-null  int64
 4   Horizontal_Distance_To_Hydrology    15120 non-null  int64
 5   Vertical_Distance_To_Hydrology      15120 non-null  int64
 6   Horizontal_Distance_To_Roadways     15120 non-null  int64
 7   Hillshade_9am                       15120 non-null  int64
 8   Hillshade_Noon                      15120 non-null  int64
 9   Hillshade_3pm                       15120 non-null  int64
 10  Horizontal_Distance_To_Fire_Points  15120 non-null  int64
 11  Wilderness_Area1                    15120 non-null  int64
 12  Wilderness_Area2                    15120 non-null  int64
 13  Wilderness_Area3                    15120 non-null  int64
 14  Wilderness_Area4                    15120 non-null  int64
 15  Soil_Type1                          15120 non-null  int64
 16  Soil_Type2                          15120 non-null  int64
 17  Soil_Type3                          15120 non-null  int64
 18  Soil_Type4                          15120 non-null  int64
 19  Soil_Type5                          15120 non-null  int64
 20  Soil_Type6                          15120 non-null  int64
 21  Soil_Type7                          15120 non-null  int64
 22  Soil_Type8                          15120 non-null  int64
 23  Soil_Type9                          15120 non-null  int64
 24  Soil_Type10                         15120 non-null  int64
 25  Soil_Type11                         15120 non-null  int64
 26  Soil_Type12                         15120 non-null  int64
 27  Soil_Type13                         15120 non-null  int64
 28  Soil_Type14                         15120 non-null  int64
 29  Soil_Type15                         15120 non-null  int64
 30  Soil_Type16                         15120 non-null  int64
 31  Soil_Type17                         15120 non-null  int64
 32  Soil_Type18                         15120 non-null  int64
 33  Soil_Type19                         15120 non-null  int64
 34  Soil_Type20                         15120 non-null  int64
 35  Soil_Type21                         15120 non-null  int64
 36  Soil_Type22                         15120 non-null  int64
 37  Soil_Type23                         15120 non-null  int64
 38  Soil_Type24                         15120 non-null  int64
 39  Soil_Type25                         15120 non-null  int64
 40  Soil_Type26                         15120 non-null  int64
 41  Soil_Type27                         15120 non-null  int64
 42  Soil_Type28                         15120 non-null  int64
 43  Soil_Type29                         15120 non-null  int64
 44  Soil_Type30                         15120 non-null  int64
 45  Soil_Type31                         15120 non-null  int64
 46  Soil_Type32                         15120 non-null  int64
 47  Soil_Type33                         15120 non-null  int64
 48  Soil_Type34                         15120 non-null  int64
 49  Soil_Type35                         15120 non-null  int64
 50  Soil_Type36                         15120 non-null  int64
 51  Soil_Type37                         15120 non-null  int64
 52  Soil_Type38                         15120 non-null  int64
 53  Soil_Type39                         15120 non-null  int64
 54  Soil_Type40                         15120 non-null  int64
 55  Cover_Type                          15120 non-null  int64
dtypes: int64(56)
memory usage: 6.5 MB

In [41]:
df2.describe()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,15120.00000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,...,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000
mean,7560.50000,2749.322553,156.676653,16.501587,227.195701,51.076521,1714.023214,212.704299,218.965608,135.091997,...,0.045635,0.040741,0.001455,0.006746,0.000661,0.002249,0.048148,0.043452,0.030357,4.000000
std,4364.91237,417.678187,110.085801,8.453927,210.075296,61.239406,1325.066358,30.561287,22.801966,45.895189,...,0.208699,0.197696,0.038118,0.081859,0.025710,0.047368,0.214086,0.203880,0.171574,2.000066
min,1.00000,1863.000000,0.000000,0.000000,0.000000,-146.000000,0.000000,0.000000,99.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3780.75000,2376.000000,65.000000,10.000000,67.000000,5.000000,764.000000,196.000000,207.000000,106.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,7560.50000,2752.000000,126.000000,15.000000,180.000000,32.000000,1316.000000,220.000000,223.000000,138.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,11340.25000,3104.000000,261.000000,22.000000,330.000000,79.000000,2270.000000,235.000000,235.000000,167.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
max,15120.00000,3849.000000,360.000000,52.000000,1343.000000,554.000000,6890.000000,254.000000,254.000000,248.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [42]:
# print corelation matrix
df2.corr()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
Id,1.000000,0.185496,0.017702,-0.020168,0.099637,0.055348,-0.033028,0.000786,0.073123,0.042524,...,0.068048,0.066887,0.022520,0.057480,0.009110,0.016040,0.086932,0.083376,0.122475,0.108363
Elevation,0.185496,1.000000,-0.011096,-0.312640,0.412712,0.122092,0.578659,0.097900,0.215782,0.089518,...,0.172349,0.123821,0.021876,0.120157,0.040571,0.073825,0.323440,0.296405,0.306755,0.016090
Aspect,0.017702,-0.011096,1.000000,0.028148,0.040732,0.056412,0.066184,-0.593997,0.324912,0.635022,...,0.003700,0.018719,0.012927,-0.004235,0.003160,-0.046309,0.043860,-0.031342,0.007208,0.008015
Slope,-0.020168,-0.312640,0.028148,1.000000,-0.055976,0.265314,-0.277049,-0.200072,-0.612613,-0.326887,...,-0.147258,0.072027,-0.030590,-0.048855,-0.004570,0.003129,-0.148342,0.051900,-0.043513,0.087722
Horizontal_Distance_To_Hydrology,0.099637,0.412712,0.040732,-0.055976,1.000000,0.652142,0.203397,-0.033803,0.080047,0.080833,...,0.138275,0.062121,0.072485,-0.015446,0.077251,-0.009549,0.131444,0.066284,0.242304,-0.010515
Vertical_Distance_To_Hydrology,0.055348,0.122092,0.056412,0.265314,0.652142,1.000000,0.011555,-0.095930,-0.132948,-0.035559,...,0.020298,0.077167,0.028910,-0.021662,0.015680,-0.020717,-0.008989,0.058981,0.227110,0.075647
Horizontal_Distance_To_Roadways,-0.033028,0.578659,0.066184,-0.277049,0.203397,0.011555,1.000000,-0.003398,0.240684,0.173882,...,0.031538,0.045797,0.021415,0.065310,0.030282,0.063302,0.197892,0.120953,0.144786,-0.105662
Hillshade_9am,0.000786,0.097900,-0.593997,-0.200072,-0.033803,-0.095930,-0.003398,1.000000,-0.013712,-0.779965,...,0.018760,-0.050739,0.004457,0.031228,0.013886,0.013207,0.012326,0.024492,-0.017234,-0.010286
Hillshade_Noon,0.073123,0.215782,0.324912,-0.612613,0.080047,-0.132948,0.240684,-0.013712,1.000000,0.614526,...,0.096261,-0.013129,0.034149,0.034638,0.029261,-0.035385,0.104682,-0.058979,-0.008203,-0.098905
Hillshade_3pm,0.042524,0.089518,0.635022,-0.326887,0.080833,-0.035559,0.173882,-0.779965,0.614526,1.000000,...,0.058244,0.024496,0.018298,0.000662,0.004545,-0.028055,0.069262,-0.056383,0.019158,-0.053399
Horizontal_Distance_To_Fire_Points,-0.068739,0.443563,-0.052169,-0.239527,0.158817,-0.015048,0.486386,0.078144,0.122098,0.043162,...,0.017055,0.049053,-0.009914,0.004767,-0.009244,0.033256,0.090648,0.047912,0.128467,-0.089389
Wilderness_Area1,-0.339861,0.330417,-0.131262,-0.152820,-0.009402,-0.117835,0.367786,0.173382,-0.014362,-0.119736,...,-0.122174,-0.115142,-0.021327,0.007086,-0.014373,0.065294,0.033239,0.022629,-0.007419,-0.230117
Wilderness_Area2,0.158484,0.261729,0.028238,-0.065923,0.087484,0.017108,-0.080758,-0.012096,0.038468,0.041908,...,0.023467,0.025601,-0.007052,0.011912,-0.004753,-0.008770,0.084694,0.029631,0.275887,0.014994
Wilderness_Area3,0.384219,0.354025,0.032578,-0.113033,0.200532,0.069884,0.124378,-0.016736,0.188611,0.131451,...,0.233901,0.219177,0.044867,0.041204,0.030237,-0.023416,0.081568,0.103275,0.017388,0.122146
Wilderness_Area4,-0.158451,-0.783651,0.075228,0.286985,-0.239303,0.027321,-0.440454,-0.137192,-0.203055,-0.046262,...,-0.146294,-0.137874,-0.025538,-0.055135,-0.017211,-0.031761,-0.150467,-0.142590,-0.118375,0.075774
Soil_Type1,-0.058451,-0.218818,-0.024538,0.099355,-0.084766,-0.034309,-0.122634,0.028399,-0.033156,-0.061726,...,-0.033907,-0.031955,-0.005919,-0.012779,-0.003989,-0.007361,-0.034874,-0.033048,-0.027436,0.015069
Soil_Type2,0.045545,-0.147947,-0.020970,-0.081498,0.024234,0.005436,-0.092474,0.055707,0.089041,0.014201,...,-0.045331,-0.042722,-0.007913,-0.017084,-0.005333,-0.009841,-0.046624,-0.044183,-0.036680,0.022627
Soil_Type3,-0.045757,-0.307523,-0.069120,0.265541,-0.089578,0.070414,-0.159434,0.244189,-0.091064,-0.300862,...,-0.057000,-0.053720,-0.009950,-0.021482,-0.006706,-0.012375,-0.058626,-0.055557,-0.046122,-0.016393
Soil_Type4,0.118214,-0.125342,0.018019,0.087841,-0.059398,-0.016543,-0.094919,0.045107,0.145950,0.018010,...,-0.053136,-0.050077,-0.009276,-0.020026,-0.006251,-0.011536,-0.054651,-0.051790,-0.042995,-0.027816
Soil_Type5,-0.041713,-0.141478,0.000343,0.074720,-0.025247,0.018550,-0.091419,-0.056873,-0.092171,-0.013319,...,-0.022969,-0.021647,-0.004010,-0.008657,-0.002702,-0.004987,-0.023624,-0.022387,-0.018585,0.027692
Soil_Type6,-0.046017,-0.187354,-0.006066,-0.047868,0.021203,0.094701,-0.135266,0.022067,0.029350,0.006573,...,-0.046346,-0.043679,-0.008090,-0.017467,-0.005452,-0.010062,-0.047668,-0.045173,-0.037501,0.006521
Soil_Type7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Soil_Type8,-0.013159,0.002934,0.001723,-0.012989,0.002819,-0.007049,0.018481,0.001942,0.007859,0.003705,...,-0.001778,-0.001676,-0.000310,-0.000670,-0.000209,-0.000386,-0.001829,-0.001733,-0.001439,-0.008133
Soil_Type9,-0.014219,-0.010571,-0.019391,-0.022220,-0.005523,-0.014610,-0.019055,0.006983,0.003198,-0.000612,...,-0.005625,-0.005302,-0.000982,-0.002120,-0.000662,-0.001221,-0.005786,-0.005483,-0.004552,-0.027012
Soil_Type10,0.032292,-0.357816,0.111959,0.255804,-0.112852,0.018305,-0.213057,-0.388943,-0.283761,0.132457,...,-0.088838,-0.083724,-0.015508,-0.033481,-0.010451,-0.019287,-0.091372,-0.086588,-0.071884,0.128972
Soil_Type11,0.063372,-0.037906,-0.034549,-0.109798,0.026150,-0.029364,-0.079474,0.025773,0.038560,0.018986,...,-0.036324,-0.034233,-0.006341,-0.013690,-0.004273,-0.007886,-0.037360,-0.035404,-0.029392,0.010228
Soil_Type12,-0.129930,0.017432,-0.044142,-0.115088,0.034306,-0.033237,0.076984,0.045241,0.051684,0.007775,...,-0.026997,-0.025443,-0.004713,-0.010175,-0.003176,-0.005861,-0.027767,-0.026313,-0.021845,-0.129985
Soil_Type13,0.015145,0.039304,0.024312,0.119863,0.026595,0.085309,0.002317,0.011151,0.002481,-0.030048,...,-0.039424,-0.037155,-0.006882,-0.014858,-0.004638,-0.008559,-0.040549,-0.038426,-0.031901,0.040528
Soil_Type14,-0.016034,-0.140619,0.001181,-0.054085,-0.111878,-0.087445,-0.071706,-0.005909,0.008796,0.019910,...,-0.023249,-0.021911,-0.004058,-0.008762,-0.002735,-0.005047,-0.023912,-0.022660,-0.018812,0.022019
Soil_Type15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Soil_Type16,-0.003794,-0.066252,0.027121,-0.064321,-0.084804,-0.070201,-0.014958,-0.002609,0.045869,0.035460,...,-0.019059,-0.017962,-0.003327,-0.007183,-0.002242,-0.004138,-0.019603,-0.018577,-0.015422,0.008793
Soil_Type17,-0.002940,-0.200663,0.029870,-0.124375,-0.159717,-0.155574,-0.080802,-0.021711,0.082792,0.078593,...,-0.044912,-0.042327,-0.007840,-0.016926,-0.005284,-0.009750,-0.046193,-0.043775,-0.036341,0.042453
Soil_Type18,-0.070252,-0.035173,-0.042140,-0.069326,-0.018282,-0.039745,-0.041192,0.025361,0.025332,0.002922,...,-0.013802,-0.013008,-0.002409,-0.005202,-0.001624,-0.002997,-0.014196,-0.013453,-0.011168,0.006312
Soil_Type19,-0.029707,0.029808,0.007570,-0.047742,-0.033946,-0.040898,0.059096,-0.006342,0.035108,0.030243,...,-0.012080,-0.011384,-0.002109,-0.004553,-0.001421,-0.002623,-0.012424,-0.011774,-0.009774,-0.031824
Soil_Type20,-0.069537,0.008548,-0.023330,-0.068508,-0.062873,-0.065710,0.046444,0.009027,0.016831,0.013306,...,-0.021063,-0.019851,-0.003677,-0.007938,-0.002478,-0.004573,-0.021664,-0.020530,-0.017044,-0.053013
Soil_Type21,0.014734,0.032509,0.018815,-0.033935,-0.025207,-0.022197,-0.004712,-0.005276,0.028241,0.023471,...,-0.007117,-0.006707,-0.001242,-0.002682,-0.000837,-0.001545,-0.007320,-0.006937,-0.005759,-0.024410
Soil_Type22,0.035739,0.146236,0.022301,-0.076393,-0.007840,-0.064122,0.107962,-0.001826,0.054116,0.042573,...,-0.033415,-0.031491,-0.005833,-0.012593,-0.003931,-0.007254,-0.034368,-0.032569,-0.027038,-0.195993
Soil_Type23,-0.017422,0.159872,0.041880,-0.184528,-0.087963,-0.144317,0.132568,-0.004735,0.127527,0.097862,...,-0.050202,-0.047312,-0.008763,-0.018920,-0.005906,-0.010899,-0.051633,-0.048930,-0.040621,-0.158762
Soil_Type24,0.034019,0.097647,0.005480,0.017982,0.046915,0.017148,0.022445,-0.047164,-0.052266,0.013918,...,-0.028754,-0.027099,-0.005020,-0.010837,-0.003383,-0.006243,-0.029575,-0.028026,-0.023267,-0.100797
Soil_Type25,0.005675,0.010586,-0.002340,0.011062,-0.004615,-0.011697,-0.006635,0.010724,-0.003911,-0.012775,...,-0.001778,-0.001676,-0.000310,-0.000670,-0.000209,-0.000386,-0.001829,-0.001733,-0.001439,-0.008133
Soil_Type26,0.031176,0.020669,-0.009775,-0.030700,0.027879,-0.016315,0.025094,0.023761,0.043268,0.006934,...,-0.013091,-0.012338,-0.002285,-0.004934,-0.001540,-0.002842,-0.013465,-0.012760,-0.010593,-0.017184
Soil_Type27,0.024141,0.040019,0.018986,0.012295,0.064616,0.047304,0.027413,-0.017156,0.025017,0.024519,...,-0.006891,-0.006494,-0.001203,-0.002597,-0.000811,-0.001496,-0.007087,-0.006716,-0.005576,-0.023109
Soil_Type28,-0.005104,-0.001077,0.026330,0.036082,0.019663,0.046287,-0.011532,-0.064360,0.009551,0.048519,...,-0.005337,-0.005029,-0.000932,-0.002011,-0.000628,-0.001159,-0.005489,-0.005201,-0.004318,-0.012202
Soil_Type29,-0.231780,0.165304,-0.063428,-0.083108,0.033854,-0.056267,0.265508,0.057190,-0.003317,-0.030254,...,-0.066813,-0.062967,-0.011663,-0.025180,-0.007860,-0.014505,-0.068718,-0.065121,-0.054062,-0.218564
Soil_Type30,-0.157515,0.048204,-0.086897,0.118725,-0.032540,-0.000083,-0.062701,0.165877,-0.139126,-0.223462,...,-0.049074,-0.046250,-0.008567,-0.018495,-0.005773,-0.010654,-0.050474,-0.047832,-0.039709,0.001393
Soil_Type31,0.025826,0.093191,0.008160,-0.076851,0.060886,0.006247,0.026668,-0.017527,0.044622,0.052232,...,-0.032765,-0.030879,-0.005720,-0.012348,-0.003855,-0.007113,-0.033699,-0.031935,-0.026512,-0.079882
Soil_Type32,0.068048,0.172349,0.003700,-0.147258,0.138275,0.020298,0.031538,0.018760,0.096261,0.058244,...,1.000000,-0.045065,-0.008347,-0.018021,-0.005625,-0.010381,-0.049181,-0.046606,-0.038692,-0.132312
Soil_Type33,0.066887,0.123821,0.018719,0.072027,0.062121,0.077167,0.045797,-0.050739,-0.013129,0.024496,...,-0.045065,1.000000,-0.007867,-0.016984,-0.005302,-0.009784,-0.046350,-0.043924,-0.036465,-0.078955
Soil_Type34,0.022520,0.021876,0.012927,-0.030590,0.072485,0.028910,0.021415,0.004457,0.034149,0.018298,...,-0.008347,-0.007867,1.000000,-0.003146,-0.000982,-0.001812,-0.008585,-0.008136,-0.006754,-0.003470
Soil_Type35,0.057480,0.120157,-0.004235,-0.048855,-0.015446,-0.021662,0.065310,0.031228,0.034638,0.000662,...,-0.018021,-0.016984,-0.003146,1.000000,-0.002120,-0.003912,-0.018535,-0.017565,-0.014582,0.114327
Soil_Type36,0.009110,0.040571,0.003160,-0.004570,0.077251,0.015680,0.030282,0.013886,0.029261,0.004545,...,-0.005625,-0.005302,-0.000982,-0.002120,1.000000,-0.001221,-0.005786,-0.005483,-0.004552,0.025726
Soil_Type37,0.016040,0.073825,-0.046309,0.003129,-0.009549,-0.020717,0.063302,0.013207,-0.035385,-0.028055,...,-0.010381,-0.009784,-0.001812,-0.003912,-0.001221,1.000000,-0.010677,-0.010118,-0.008400,0.071210
Soil_Type38,0.086932,0.323440,0.043860,-0.148342,0.131444,-0.008989,0.197892,0.012326,0.104682,0.069262,...,-0.049181,-0.046350,-0.008585,-0.018535,-0.005786,-0.010677,1.000000,-0.047936,-0.039795,0.257810
Soil_Type39,0.083376,0.296405,-0.031342,0.051900,0.066284,0.058981,0.120953,0.024492,-0.058979,-0.056383,...,-0.046606,-0.043924,-0.008136,-0.017565,-0.005483,-0.010118,-0.047936,1.000000,-0.037712,0.240384
Soil_Type40,0.122475,0.306755,0.007208,-0.043513,0.242304,0.227110,0.144786,-0.017234,-0.008203,0.019158,...,-0.038692,-0.036465,-0.006754,-0.014582,-0.004552,-0.008400,-0.039795,-0.037712,1.000000,0.205851
Cover_Type,0.108363,0.016090,0.008015,0.087722,-0.010515,0.075647,-0.105662,-0.010286,-0.098905,-0.053399,...,-0.132312,-0.078955,-0.003470,0.114327,0.025726,0.071210,0.257810,0.240384,0.205851,1.000000

In [45]:
import numpy as np

In [46]:
# remove less co related rows by intailize threshold
threshold=0.4
corr_matrix=df2.corr().abs()
upper=corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(bool))
to_drop=[column for column in upper.columns if any(upper[column]>threshold)]
print(to_drop)

['Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_Type29', 'Soil_Type30']

In [47]:
# list input and output
x=df2.drop(['Cover_Type','Id','Soil_Type7','Soil_Type15'],axis=1)
y=df2['Cover_Type']

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [60]:
model=keras.Sequential([
    keras.layers.Dense(256,activation='relu',input_shape=(52,)),
    keras.layers.Dense(128,activation='relu'),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(32,activation='relu'),
    keras.layers.Dense(16,activation='relu'),
    keras.layers.Dense(8,activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x_train,y_train,epochs=50,validation_split=0.2,batch_size=32)

Epoch 1/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.2859 - loss: 5.8182 - val_accuracy: 0.2471 - val_loss: 3.0796
Epoch 2/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.3955 - loss: 2.1009 - val_accuracy: 0.4674 - val_loss: 1.4038
Epoch 3/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.4414 - loss: 1.6154 - val_accuracy: 0.5029 - val_loss: 1.2696
Epoch 4/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4887 - loss: 1.3351 - val_accuracy: 0.5079 - val_loss: 1.1976
Epoch 5/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5162 - loss: 1.2395 - val_accuracy: 0.5401 - val_loss: 1.1311
Epoch 6/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5374 - loss: 1.1141 - val_accuracy: 0.5963 - val_loss: 0.9663
Epoch 7/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5817 - loss: 0.9937 - val_accuracy: 0.5971 - val_loss: 0.9738
Epoch 8/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5569 - loss: 1.0626 - val_accuracy: 0.5938 - val_loss: 0.9514
Epoch 9/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5932 - loss: 0.9495 - val_accuracy: 0.5992 - val_loss: 0.9437
Epoch 10/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5935 - loss: 0.9478 - val_accuracy: 0.6207 - val_loss: 0.8668
Epoch 11/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5948 - loss: 0.9366 - val_accuracy: 0.6169 - val_loss: 0.9172
Epoch 12/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.6109 - loss: 0.8949 - val_accuracy: 0.6380 - val_loss: 0.8696
Epoch 13/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6159 - loss: 0.8763 - val_accuracy: 0.6500 - val_loss: 0.8250
Epoch 14/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6263 - loss: 0.8748 - val_accuracy: 0.6653 - val_loss: 0.8082
Epoch 15/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6322 - loss: 0.8469 - val_accuracy: 0.6583 - val_loss: 0.8105
Epoch 16/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6370 - loss: 0.8548 - val_accuracy: 0.6112 - val_loss: 0.9288
Epoch 17/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6333 - loss: 0.8412 - val_accuracy: 0.6719 - val_loss: 0.7935
Epoch 18/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6411 - loss: 0.8317 - val_accuracy: 0.6839 - val_loss: 0.7653
Epoch 19/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6522 - loss: 0.7908 - val_accuracy: 0.6070 - val_loss: 0.8943
Epoch 20/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.6485 - loss: 0.8095 - val_accuracy: 0.6517 - val_loss: 0.8051
Epoch 21/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6546 - loss: 0.8107 - val_accuracy: 0.6607 - val_loss: 0.8176
Epoch 22/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6768 - loss: 0.7645 - val_accuracy: 0.6310 - val_loss: 0.8409
Epoch 23/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6799 - loss: 0.7498 - val_accuracy: 0.6612 - val_loss: 0.7999
Epoch 24/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6751 - loss: 0.7553 - val_accuracy: 0.6442 - val_loss: 0.8230
Epoch 25/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6780 - loss: 0.7608 - val_accuracy: 0.6698 - val_loss: 0.7452
Epoch 26/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6918 - loss: 0.7222 - val_accuracy: 0.6785 - val_loss: 0.7702
Epoch 27/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6849 - loss: 0.7378 - val_accuracy: 0.7021 - val_loss: 0.7104
Epoch 28/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7015 - loss: 0.7068 - val_accuracy: 0.6579 - val_loss: 0.8020
Epoch 29/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7050 - loss: 0.7049 - val_accuracy: 0.6897 - val_loss: 0.7627
Epoch 30/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6967 - loss: 0.7092 - val_accuracy: 0.6360 - val_loss: 0.9248
Epoch 31/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7106 - loss: 0.6877 - val_accuracy: 0.6781 - val_loss: 0.7935
Epoch 32/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7058 - loss: 0.7029 - val_accuracy: 0.6901 - val_loss: 0.7320
Epoch 33/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7205 - loss: 0.6667 - val_accuracy: 0.7343 - val_loss: 0.6598
Epoch 34/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7260 - loss: 0.6618 - val_accuracy: 0.7335 - val_loss: 0.6770
Epoch 35/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7183 - loss: 0.6679 - val_accuracy: 0.6789 - val_loss: 0.7841
Epoch 36/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7199 - loss: 0.6675 - val_accuracy: 0.6583 - val_loss: 0.8272
Epoch 37/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7202 - loss: 0.6666 - val_accuracy: 0.7347 - val_loss: 0.6726
Epoch 38/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7352 - loss: 0.6303 - val_accuracy: 0.7467 - val_loss: 0.6415
Epoch 39/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7228 - loss: 0.6499 - val_accuracy: 0.7450 - val_loss: 0.6273
Epoch 40/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7397 - loss: 0.6268 - val_accuracy: 0.7029 - val_loss: 0.6990
Epoch 41/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7473 - loss: 0.6067 - val_accuracy: 0.7074 - val_loss: 0.7058
Epoch 42/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7532 - loss: 0.6009 - val_accuracy: 0.7421 - val_loss: 0.6727
Epoch 43/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7444 - loss: 0.6103 - val_accuracy: 0.7446 - val_loss: 0.6290
Epoch 44/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7568 - loss: 0.5926 - val_accuracy: 0.7500 - val_loss: 0.6110
Epoch 45/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7640 - loss: 0.5740 - val_accuracy: 0.7632 - val_loss: 0.5860
Epoch 46/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7666 - loss: 0.5799 - val_accuracy: 0.7417 - val_loss: 0.6492
Epoch 47/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7603 - loss: 0.5736 - val_accuracy: 0.7517 - val_loss: 0.6035
Epoch 48/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7728 - loss: 0.5578 - val_accuracy: 0.7521 - val_loss: 0.6498
Epoch 49/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7693 - loss: 0.5629 - val_accuracy: 0.7632 - val_loss: 0.5817
Epoch 50/50
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7682 - loss: 0.5617 - val_accuracy: 0.7521 - val_loss: 0.6168

In [62]:
acc,loss=model.evaluate(x_test,y_test)
print(acc,loss)

95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7480 - loss: 0.6257
0.6257121562957764 0.7480158805847168